/** Generated by Semantik */

import java.awt.*;
import java.awt.event.*;
import java.net.*;
import java.applet.*;
import javax.swing.*;

public class Kadapplet extends JApplet
{
	Mapview m_mapview;

	public void init()
	{
		// System Look and Feel
		String laf = UIManager.getSystemLookAndFeelClassName();
		try
		{
			UIManager.setLookAndFeel(laf);
			// UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
		} catch (UnsupportedLookAndFeelException exc) {
			System.err.println("Warning: UnsupportedLookAndFeel: " + laf);
		} catch (Exception exc) {
			System.err.println("Error loading " + laf + ": " + exc);
		}

		m_mapview = new Mapview();
		getContentPane().add(m_mapview, BorderLayout.CENTER);
		m_mapview.setPreferredSize(new Dimension(200, 300));
	}

	public void stop()
	{
		if (m_mapview != null)
		{
			getContentPane().remove(m_mapview);
			m_mapview = null;
		}
	}
}

